version: "3.4"
services: 
    question_app:
        container_name: question_app
        build: .
        env_file: ./config/env/config.env
        ports: 
            - 3000:3000
        depends_on: 
            - mongodb
    mongodb:
        image: mongo 
        ports: 
            - 27017:27017
        volumes:
            - question-data:/data/db
 
volumes: 
    question-data: